version: "3.5"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: CardDeliveryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: AuthService.Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    links:
      - db  
  card-service:
    container_name: card-service
    build:
      context: .
      dockerfile: CardService.Dockerfile
    ports:
      - "4444:4444"
    environment:
      - NODE_ENV=development
    links:
      - db 
      - auth-service
  delivery-service:
    container_name: delivery-service
    build:
      context: .
      dockerfile: DeliveryService.Dockerfile
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=development
    links:
      - db 
      - auth-service 
  user-address-service:
    container_name: user-address-service
    build:
      context: .
      dockerfile: UserAddressService.Dockerfile
    ports:
      - "6666:6666"
    environment:
      - NODE_ENV=development
    links:
      - db   
      - auth-service          
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: OrderService.Dockerfile
    ports:
      - "7777:80"  
    links:
      - db   
      - auth-service      